[package]
name = "libcgc"
version = "0.1.0"
edition = "2024"
homepage = "https://liphium.dev/libcgc"
repository = "https://github.com/Liphium/libcgc"
license-file = "LICENSE"

[dependencies]
ml-dsa = "0.0.4"
ml-kem = "0.2.1"
rand = "0.8.0"
sha3 = "0.10.8"
sodoken = "0.1.0"
x-wing = "0.0.1-pre.1"
